dependency_scanning:
  image: antzsnyk/gradle-7.6-nodejs-20-jq-1.6

  stage: test
  script:

    - npm install -g snyk
    - npm install -g snyk-delta

    - snyk auth $SNYK_TOKEN
    - ./snyk_delta_all_projects.sh --org=${SNYK_BASELINE_ORG_ID} --remote-repo-url=$CI_PROJECT_DIR --severity-threshold=medium
    - snyk monitor --all-projects --org=${SNYK_BASELINE_ORG_ID} --remote-repo-url=$CI_PROJECT_DIR

  # Save report to artifacts
  #artifacts:
  #  when: always
  #  paths:
  #    - snyk_results.html