dependency_scanning:
  image: antzsnyk/gradle-7.4.2-nodejs-20
  stage: test
  script:
    # Install npm, snyk, and snyk-to-html
    #- apt install 
    #- npm install -g npm@latest
    - npm install -g snyk
    - npm install -g snyk-delta
    #- npm install snyk-to-html -g
    # Run snyk help, snyk auth, snyk monitor, snyk test to break build and out report

    - snyk --help
    #- curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
    #- chmod +x ./snyk
    #- echo SnykProjName:${CI_PROJECT_DIR}:${CI_PROJECT_NAME}:${CI_PROJECT_PATH_SLUG}:${CI_PROJECT_PATH}:${CI_PROJECT_ROOT_NAMESPACE}:${CI_PROJECT_TITLE} # <--- We're adding these GitLab variables to the Snyk monitor command directly below
    - snyk auth $SNYK_TOKEN
    - snyk monitor --org=$SNYK_ORG_ID --remote-repo-url=$CI_PROJECT_DIR # <---the target name in Snyk UI will be <the root dir>
    #- ./snyk_delta_all_projects.sh --org=$SNYK_ORG_ID --severity-threshold=high --print-dep-path --setPassIfNoBaseline true
  
    #- snyk test --json --org=$SNYK_ORG_ID | snyk-to-html -o snyk_results.html
  # Save report to artifacts
  #artifacts:
  #  when: always
  #  paths:
  #    - snyk_results.html