name: "Snyk Gradle/OS Scan"

on:
  push:
    branches:
      - 'demo*'  # Include any branch starting with demo
  pull_request:
    branches:
      - main

jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk Config'
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v1

      # Install and Authenticate to Snyk
      - name: Install Snyk & Authenticate
        run: |
          sudo npm install -g snyk
          sudo npm install -g snyk-delta
          snyk auth ${SNYK_TOKEN}

      # Run Snyk OS
      - name: Run Snyk OS
        run: |
          ./snyk_delta_all_projects.sh --all-projects --org=6d36ac7a-c75b-4179-8e73-6dd4d3fc8343 --remote-repo-url=gradle-test-cli
        continue-on-error: true



